# Generated by Django 3.0.7 on 2020-06-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200607_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='finish_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
