# Generated by Django 3.0.7 on 2020-06-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200607_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
    ]
